### PR TITLE
Dep/upgrade plugin catalog

### PR DESCRIPTION
**Pull request by wrousseau**
Hi!

I've made two updates:
- one to the `@backstage/plugin-catalog` plugin, which does not include any breaking change. Only minor change with 0.3.x has to do with stuff it exported and it does not seem your repository imports anything from it. It's actually a bit weird because it seems it's not used anywhere. Should we remove it?
- another update to documentation as an exported field has changed name

Cheers

### CODE REVIEW

**Review by padraigobrien — DISMISSED** [review]

**Comment by wrousseau** [comment]
Sorry @padraigobrien seems like I forgot a change in the README, just amended my commit

**Comment by dtuite** [comment]
> It's actually a bit weird because it seems it's not used anywhere. Should we remove it?

@padraigobrien any thoughts on this question in the description?

**Comment by padraigobrien** [comment]
Good catch @dtuite , I missed that, apologies to you @wrousseau , newly scaffolded plugins to not include this dependency in package.json, coupled with the fact that it is not being used in this plugin, i think it should be OK to remove it

**Comment by padraigobrien** [comment]
Hi @wrousseau , i spun up a local copy of this with the change, it worked fine.

**Comment by wrousseau** [comment]
I've removed the dependency.
If you're ok to merge this and do a publication on npm, would be great :)

I've also ran "depcheck" by the way, it has also detected that @backstage/theme, history, react-router are not being used

**Comment by padraigobrien** [comment]
amazing, thanks for running that, Lets remove them as well, we might as well do a good cleanup while here.

**Comment by padraigobrien** [comment]
can you do a version bump for me on this and the other PR?

**Comment by wrousseau** [comment]
Done for both :)

**Comment by padraigobrien** [comment]
I think you need , history

**Comment by wrousseau** [comment]
Yes that's weird, depcheck has a false negative for it. I've re-added it

**Review by padraigobrien — APPROVED** [review]

**Comment by wrousseau** [comment]
@padraigobrien it seems like the npm publish step failed :(

**Pull request merged**
